# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://www.xiaoyimate.com/api/form-submits-jin
Content-Type: application/json

{
    "form": "nmTE0V",
    "form_name": "匹配单2019.4.5",
    "entry": {
        "serial_number": 38,
        "field_85": "",
        "field_123": "",
        "field_86": "15-17",
        "field_87": [
            "33-35"
        ],
        "field_88": "150-160",
        "field_89": [
            "161-165"
        ],
        "field_90": "偏瘦",
        "field_9": [
            "强壮"
        ],
        "field_93": {
            "province": "内蒙古自治区",
            "city": "",
            "district": "",
            "street": ""
        },
        "field_94": {
            "province": "山西省",
            "city": "",
            "district": "",
            "street": ""
        },
        "field_95": {
            "province": "吉林省",
            "city": "",
            "district": "",
            "street": ""
        },
        "field_96": {
            "province": "内蒙古自治区",
            "city": "",
            "district": "",
            "street": ""
        },
        "field_97": "本科",
        "field_17": [
            "大专"
        ],
        "field_100": "体制内",
        "field_101": [
            "体制内"
        ],
        "field_104": "3万以下",
        "field_29": [
            "6万-10万"
        ],
        "field_30": [
            "刚好月光"
        ],
        "field_31": [
            "适当理财"
        ],
        "field_105": "基督教",
        "field_33": [
            "天主教"
        ],
        "field_108": "女",
        "field_109": "男",
        "field_110": "差",
        "field_37": [
            "差"
        ],
        "field_111": "差",
        "field_39": [
            "差"
        ],
        "field_112": [
            "眉眼",
            "下巴",
            "耳垂"
        ],
        "field_113": [
            "眉眼",
            "耳垂"
        ],
        "field_42": [],
        "field_124": [
            "怯生"
        ],
        "field_45": [
            "冷场"
        ],
        "field_46": [
            "深沉"
        ],
        "field_47": [
            "深沉"
        ],
        "field_48": [
            "不想扫兴勉强同意"
        ],
        "field_49": [
            "如果对方坚持会妥协"
        ],
        "field_50": [
            "主动"
        ],
        "field_51": [
            "主动"
        ],
        "field_118": [
            "率性不拘"
        ],
        "field_119": [
            "条理缜密"
        ],
        "field_52": [
            "易纠结"
        ],
        "field_53": [
            "干脆果断"
        ],
        "field_54": [
            "安静的做自己的事"
        ],
        "field_55": [
            "安静的做自己的事"
        ],
        "field_57": [
            "一见钟情"
        ],
        "field_58": [
            "一见钟情"
        ],
        "field_59": [
            "有自己的空间"
        ],
        "field_60": [
            "有自己的空间"
        ],
        "field_61": [
            "隐隐暗示对方"
        ],
        "field_62": [
            "隐隐暗示对方"
        ],
        "field_65": [
            "会存钱，但不会透支购买"
        ],
        "field_66": [
            "会存钱，但不会透支购买"
        ],
        "field_83": "11",
        "x_field_weixin_nickname": "啊托",
        "x_field_weixin_gender": "男",
        "x_field_weixin_country": "中国",
        "x_field_weixin_province_city": {
            "province": "浙江",
            "city": "温州"
        },
        "x_field_weixin_openid": "oMzbs1AjHHELJZI4So4nR5W8ZYs4",
        "x_field_weixin_headimgurl": "http://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83erHsT073H36WbeJUj0EMBUwLELsgQlFYUVSjfK0emCGqPzPVM2iarANACplKQxib2FHYwf2NUicrl7ew/132",
        "creator_name": "",
        "created_at": "2019-04-20T08:03:44.390Z",
        "updated_at": "2019-04-21T12:03:44.757Z",
        "info_remote_ip": "125.110.205.193"
    }
}

###

#更新表单地址
GET http://www.xiaoyimate.com/wx/menu/wxba1e1e0cfc55f4a9/create-xy
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTU1NjUxNTg5NH0.qzGYPeYU2wY-bYesoD603WToFUswWKBznFx9iECkpAkz49ycnQ4bD-n4NRLq2skEoU9CrIRPtLJZUdnCw8ZQIw

###

GET http://localhost:9000/api/form-fields/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTU1NjUxNTg5NH0.qzGYPeYU2wY-bYesoD603WToFUswWKBznFx9iECkpAkz49ycnQ4bD-n4NRLq2skEoU9CrIRPtLJZUdnCw8ZQIw

###
