# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8081/api/form-submits-jin
Content-Type: application/json

{
    "form": "nmTE0V",
    "form_name": "基础匹配单",
    "entry": {
        "serial_number": 162,
        "field_85": "男",
        "field_123": "女",
        "field_86": "27-29",
        "field_87": [
            "27-29"
        ],
        "field_88": "161-165",
        "field_89": [
            "161-165"
        ],
        "field_93": {
            "province": "浙江省",
            "city": "温州市",
            "district": "鹿城区",
            "street": ""
        },
        "field_94": {
            "province": "浙江省",
            "city": "温州市",
            "district": "鹿城区",
            "street": ""
        },
        "field_95": {
            "province": "浙江省",
            "city": "温州市",
            "district": "鹿城区",
            "street": ""
        },
        "field_96": {
            "province": "浙江省",
            "city": "温州市",
            "district": "鹿城区",
            "street": ""
        },
        "field_97": "本科",
        "field_17": [
            "大专",
            "本科"
        ],
        "field_100": "体制内",
        "field_101": [
            "体制内",
            "工薪族",
            "经商"
        ],
        "field_104": "10万-15万",
        "field_29": [
            "3万-6万",
            "6万-10万"
        ],
        "field_105": "基督教",
        "field_33": [
            "基督教"
        ],
        "field_42": [],
        "field_83": "kikimiss0",
        "x_field_weixin_nickname": "🤔 Street  view",
        "x_field_weixin_gender": "男",
        "x_field_weixin_country": "中国",
        "x_field_weixin_province_city": {
            "province": "浙江",
            "city": "温州"
        },
        "x_field_weixin_openid": "oMzbs1AJteCaE7GovHBTnHADu6ho",
        "x_field_weixin_headimgurl": "http://thirdwx.qlogo.cn/mmopen/vi_32/LSJWMxRwSdCG9JFBCPbwcTZpLarQuqRvTFG8o8BxObrico1xIjBM6yKe4aiaz8hNUJXzdStaON9InufftUjdDAfQ/132",
        "creator_name": "",
        "created_at": "2019-05-05T06:50:27.292Z",
        "updated_at": "2019-05-05T06:50:27.648Z",
        "info_remote_ip": "61.164.136.35"
    }
}







###

#更新表单地址
GET http://www.xiaoyimate.com/wx/menu/wxba1e1e0cfc55f4a9/create-xy
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTU1NjUxNTg5NH0.qzGYPeYU2wY-bYesoD603WToFUswWKBznFx9iECkpAkz49ycnQ4bD-n4NRLq2skEoU9CrIRPtLJZUdnCw8ZQIw

###

GET http://localhost:9000/api/form-fields/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTU1NjUxNTg5NH0.qzGYPeYU2wY-bYesoD603WToFUswWKBznFx9iECkpAkz49ycnQ4bD-n4NRLq2skEoU9CrIRPtLJZUdnCw8ZQIw

###

#获取token（系统账号密码登入）
POST http://localhost:8081/api/authenticate
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

GET http://localhost:8081/api/user-matches-regenerate
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTU1NjQzOTE3M30.wfJjPg3S5cLokkz0MlJ9ZsHelRECgqmld9XrETzQvppKFqY1w1FXA2FeDcTxGNoc1qtzX6KuURekPPEBSvTPUA

###
